// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth/internal/conf"
	"auth/internal/server"
	"auth/internal/service/v1"
	service2 "auth/internal/service/version"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	authService := service.NewAuthService()
	versionService := service2.NewVersionService()
	grpcServer := server.NewGRPCServer(confServer, authService, versionService, logger)
	httpServer := server.NewHTTPServer(confServer, authService, versionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
